### ISSUE TITLE
Problems with Plug - but maybe not?

### ISSUE THREAD

**Issue by BrianHicks** [tonini/alchemist.el#64] opened 2015-04-09 22:13 UTC
Hi, I'm an Elixir newbie, using Alchemist. I've run across something that I'm not sure if is a bug in my code, my usage, or alchemist. Since I'm not sure, I've created a minimal project. It's here: https://github.com/BrianHicks/testplug

The problem is: I get an error on the `use Plug.Router` line in `lib/testplug.ex` when compiling with `alchemist-compile-this-buffer`:

```
elixirc /Users/brianhicks/code/sandbox/testplug/lib/testplug.ex
lib/testplug.ex:1: warning: redefining module TestPlug

== Compilation error on file lib/testplug.ex ==
** (CompileError) lib/testplug.ex:2: module Plug.Router is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/testplug.ex:2: TestPlug (module)
```

However, the tests all pass and the app will run and respond when started with Cowboy. So I'm at a bit of a loss here - is there something else I have to configure? I've pulled down the deps... are they in some weird location I need to set?

**Comment by jtmoulia** [comment] 2015-04-09 22:51
Hey Brian, I think the issue is that `alchemist-compile-this-buffer` will try compile the file independent of the mix project. Without the paths to the compiled files, you get the error you're seeing.

You should have better luck with `alchemist-mix-compile`

**Comment by BrianHicks** [comment] 2015-04-10 11:23
hmm, ok. That compiles, but I still get errors in flycheck. Is there a setting for that?

**Comment by jtmoulia** [comment] 2015-04-15 18:37
Hey, the flycheck issue you're seeing has the same cause (`elixirc` vs `mix compile`), but is due to code defined [in flycheck](https://github.com/flycheck/flycheck/blob/23606b44c42684ec83bf20e71295ef11f4415c56/flycheck.el#L5626). 

@BrianHicks you could report this to [flycheck](https://github.com/flycheck/flycheck/issues/new). I'll bet they've run into similar issues, and can give better advice.

**Comment by tonini** [comment] 2015-05-16 10:33
@jtmoulia @BrianHicks Whats the status about this issue? I think @jtmoulia was right about the issue here. If you got errors `flycheck` specific, maybe you should talk with the people from the project.

@BrianHicks If you get `flycheck`and `elixir` working nice together inside emacs, please give us a report about it. :)

**Comment by tonini** [comment] 2015-05-22 07:13
I'll close this issue because it looks like that's an issue with `flycheck`.

Thanks

**Closed by tonini** 2015-05-22 07:13 UTC
