### ISSUE TITLE
cannot type capital "T" in the beginning of IEx as it is binded

### ISSUE THREAD

**Issue by johnmedina1010** [tonini/alchemist.el#258] opened 2016-10-02 01:18 UTC
capital "T" is binded to  evil-find-char-to-backward as shown in bindings.

Is there any way to edit this binding?

**Comment by gaydenko** [comment] 2016-10-02 01:58
At my case `T` is just the next command prefix (no spacemacs in use). It is interesting, prefix `T` results in prefix `A`, and the last one results in prefix `B`. Do you see `TAB`? :) It seems somewhere a key name is treated as a string.

**Comment by walter** [comment] 2016-10-02 19:35
I'm experiencing this as well (example is trying to type `Ecto.DateTime` in `*Alchemist-IEx*` buffer).

Using Aquamacs 3.3  GNU Emacs 25.1.1 and alchemist package 20160921.832. I'm haven't set up `evil-mode` that I'm aware of.

**Comment by walter** [comment] 2016-10-02 19:40
Updated alchemist package to 20160926.2346 and still experiencing it.

**Comment by walter** [comment] 2016-10-02 21:52
anli in Slack pointed me to `which-key` package and the use of the corresponding mode to track down key mapping options. That led me to discover the following:

Looks like `T-A-B` (i.e. shift-t, shift-a, shift-b) maps to `company-complete`. `T` and `A` are prefixes.

Which is, of course, what the `tab` key is mapped to as well judging by the behavior. So I imagine somewhere in the code (may be another package, of course), the string `TAB` is swapped for the what was meant to be the tab character representation.

**Comment by asummers** [comment] 2016-10-02 22:52
I am unable to reproduce on an earlier version. Looks like this commit added the TAB binding. Perhaps it should be `<tab>`?

https://github.com/tonini/alchemist.el/commit/f7b0959105abbb27936577f9427310c1c14417be

**Comment by tonini** [comment] 2016-10-03 05:07
It's fixed on master thanks to @syohex and @walter 💛

**Closed by tonini** 2016-10-03 05:07 UTC
